---
title: "Instructions"
output: html_document
---

# Overview

IsoQC is an outlier detection app specialized for observations of isotopes in precipitation.
Brief usage instructions are available below. For further specifics, see Supplementary Sect. 2 of the *Hatvani et al. (2025)* article.

## Instructions

The *IsoQC* app allows users to upload their own datasets to analyze stable isotope records from precipitation samples. The data upload module supports MS Excel (.xlsx, .xls) and CSV (.csv) with a maximum file size limit of 500 MB. To ensure proper functionality, the uploaded data must contain specific columns: Station (measurement station name or identifier), Date (observation date in a standard format such as DD/MM/YYYY or DD-MM-YYYY), Longitude and Latitude (geographic coordinates in decimal degrees), Altitude, and $\delta^{18}O$ (‰) and $\delta^{2}H$ (‰). Date values should be properly formatted in the case of MS Excel files, and if necessary, users can manually specify the date format before finalizing the upload in the case of CSV files. Longitude and latitude must be within valid geographic ranges, and missing values are allowed, though rows where both $\delta^{18}O$ and $\delta^{2}H$ are missing will be automatically excluded.  The file should not contain extra header rows, with only the first row dedicated to column names.
After any change in the dashboard setting it takes a couple of seconds for the app to respond.

To eliminate the gaps in the data series, please fill the missing month of the selected station with a dummy value (must be numeric) and upload it to the WebUI. This way, an average value will be calculated in IsoQC for that particular month, which can then potentially be used to input the gap in the data series.

Disclaimer: Any uploaded data is there for preview and testing, no data is saved or stored permanently.